name: Backend CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to server'
        required: true
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: islombekturakulov/mybudget-backend
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-home-cache-cleanup: true

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-home-cache-cleanup: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
            type=gha
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
            type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILDKIT_INLINE_CACHE=1

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Create directory if it doesn't exist
            sudo mkdir -p /opt/mybudget/backend
            sudo chown -R $USER:$USER /opt/mybudget/backend
            cd /opt/mybudget/backend
            
            # Check Docker Swarm status
            echo "Checking Docker Swarm status..."
            docker info | grep Swarm
            
            # Check node status
            echo "Checking node status..."
            docker node ls
            
            # Clean up existing resources
            echo "Cleaning up existing resources..."
            docker stack rm backend || true
            sleep 10
            docker network rm backend_backend backend_public || true
            sleep 5
            
            # Create .env file
            cat > .env << EOL
            PG_USER=${{ secrets.PG_USER }}
            PG_DATABASE=${{ secrets.PG_DATABASE }}
            GITHUB_OWNER=islombekturakulov
            TAG=${{ github.sha }}
            LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}
            EOL
            
            # Verify environment variables
            echo "Verifying environment variables..."
            if [ -z "${{ secrets.PG_USER }}" ] || [ -z "${{ secrets.PG_DATABASE }}" ] || [ -z "${{ secrets.PG_PASSWORD }}" ] || [ -z "${{ secrets.JWT_SECRET }}" ]; then
              echo "Error: Missing required environment variables"
              exit 1
            fi
            
            # Create secrets directory if it doesn't exist
            mkdir -p secrets
            
            # Create password files
            echo "${{ secrets.PG_PASSWORD }}" > secrets/pg_password.txt
            echo "${{ secrets.JWT_SECRET }}" > secrets/app_jwt_secret.txt
            
            # Set proper permissions
            chmod 600 secrets/pg_password.txt secrets/app_jwt_secret.txt
            
            # Login to GitHub Container Registry with proper authentication
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Verify login and pull the image
            echo "Verifying image access..."
            docker pull ghcr.io/islombekturakulov/mybudget-backend:${{ github.sha }}
            
            # Copy docker-compose.yml from repository
            cp /opt/mybudget/backend/docker-compose.yml .
            
            # Pull latest images and deploy
            echo "Deploying stack..."
            docker stack deploy -c docker-compose.yml backend --with-registry-auth

            # Wait for services to be ready
            echo "Waiting for services to be ready..."
            sleep 30

            # Check service status
            echo "Checking service status..."
            docker service ls

            # Check if all replicas are running
            echo "Checking replicas..."
            docker service ps backend_backend --no-trunc || true
            docker service ps backend_database --no-trunc || true
            docker service ps backend_traefik --no-trunc || true

            # Check network connectivity
            echo "Checking networks..."
            docker network ls | grep backend

            # Check logs for any immediate issues
            echo "Checking service logs..."
            docker service logs --tail 50 backend_backend || true
            docker service logs --tail 50 backend_database || true
            docker service logs --tail 50 backend_traefik || true

            # Check if ports are open
            echo "Checking if ports are open..."
            if command -v netstat &> /dev/null; then
              netstat -tulpn | grep -E '80|443' || true
            else
              echo "netstat not available, skipping port check"
            fi

            # Verify health endpoints
            echo "Verifying health endpoints..."
            curl -v http://89.169.144.44/ping || echo "Backend health check failed"

            # Check resource usage
            echo "Checking resource usage..."
            docker stats --no-stream

            # Final status
            echo "Deployment completed. Checking final status..."
            docker stack services backend 